FROM microsoft/mssql-server-windows

MAINTAINER Jared Atkinson <jared@invoke-ir.com>

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

EXPOSE 1433

WORKDIR c:\\windows\\temp

# create directory within SQL container for database files
RUN powershell -Command (mkdir C:\\MSSQL)

#copy the database files from host to container
COPY ACEWebService.mdf C:\\MSSQL
COPY ACEWebService_log.ldf C:\\MSSQL

ENV ACCEPT_EULA=Y

ENV attach_dbs="[{'dbName':'ACEWebService','dbFiles':['C:\\MSSQL\\ACEWebService.mdf','C:\\MSSQL\\ACEWebService_log.ldf']}]"
